// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Musical Drops",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Musical Drops",
            targets: ["AppModule"],
            bundleIdentifier: "com.archergs.Musical-Drops",
            teamIdentifier: "5US2W9UQ66",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .music
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Drums/Kick.mp3"),
                .copy("Drums/Snare.mp3"),
                .copy("Drums/Hat.mp3"),
                .copy("Guitar/AGuitar.mp3"),
                .copy("Guitar/BGuitar.mp3"),
                .copy("Guitar/CGuitar.mp3"),
                .copy("Guitar/DGuitar.mp3"),
                .copy("Guitar/EGuitar.mp3"),
                .copy("Guitar/FGuitar.mp3"),
                .copy("Guitar/GGuitar.mp3"),
                .copy("Piano/APiano.mp3"),
                .copy("Piano/BPiano.mp3"),
                .copy("Piano/CPiano.mp3"),
                .copy("Piano/DPiano.mp3"),
                .copy("Piano/EPiano.mp3"),
                .copy("Piano/FPiano.mp3"),
                .copy("Piano/GPiano.mp3")
            ]
        )
    ]
)
